# Generated by Django 3.0.5 on 2020-04-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtracaoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_inicio', models.DateTimeField()),
                ('data_horario_fim', models.DateTimeField()),
                ('apresentador', models.CharField(max_length=100, null=True)),
                ('local', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Palestra', 'Palestra'), ('Oficina', 'Oficina'), ('Visita Técnica', 'Visita Técnica')], max_length=30)),
                ('vagas', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('valor_inscricao', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoAtracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
