# Generated by Django 3.0.6 on 2020-06-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoevento',
            name='associado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='atracoes',
            field=models.ManyToManyField(through='eventos.InscricaoAtracao', to='eventos.AtracaoEvento'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='inscricaoatracao',
            name='atracao_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.AtracaoEvento'),
        ),
        migrations.AddField(
            model_name='inscricaoatracao',
            name='inscricao_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.InscricaoEvento'),
        ),
    ]
