from .Areas import *
from .Associados import *
from .Reunioes import *
from .Diretores import *
from .Diretorio import *
from .Egressos import *
from .Gestor import *
from .Grupos import *
from .LinksCadastro import *
