# Generated by Django 3.0.6 on 2020-06-01 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import financeiro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('efetivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('servico', models.BooleanField(default=False)),
                ('arquivado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('efetivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemporadaEncomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('data_fim', models.DateField(default=financeiro.models.mais_d)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('efetivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('desconto', models.FloatField(default=0)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financeiro.Produto')),
                ('quantidade', models.PositiveIntegerField()),
                ('quantidade_minima', models.PositiveIntegerField(default=0)),
                ('quantidade_encomenda', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EntradaFinanceira')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Venda')),
            ],
        ),
    ]
