# Generated by Django 3.0.6 on 2020-06-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='associado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='entradas',
            field=models.ManyToManyField(through='financeiro.VendaEntrada', to='financeiro.EntradaFinanceira'),
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(through='financeiro.VendaProduto', to='financeiro.Produto'),
        ),
        migrations.AddField(
            model_name='transferenciafinanceira',
            name='carteira_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_para', to='financeiro.Carteira'),
        ),
        migrations.AddField(
            model_name='transferenciafinanceira',
            name='carteira_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_de', to='financeiro.Carteira'),
        ),
        migrations.AddField(
            model_name='temporadaencomenda',
            name='produtos',
            field=models.ManyToManyField(related_name='temporadas_encomenda', to='financeiro.Produto'),
        ),
        migrations.AddField(
            model_name='saidafinanceira',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.Carteira'),
        ),
        migrations.AddField(
            model_name='recibopagamento',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recibopagamento',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EntradaFinanceira'),
        ),
        migrations.AddField(
            model_name='entradafinanceira',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.Carteira'),
        ),
        migrations.AddField(
            model_name='encomendaproduto',
            name='encomenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Encomenda'),
        ),
        migrations.AddField(
            model_name='encomendaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.Produto'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='produtos',
            field=models.ManyToManyField(through='financeiro.EncomendaProduto', to='financeiro.Produto'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='temporada_encomenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.TemporadaEncomenda'),
        ),
    ]
