# Generated by Django 3.0.6 on 2020-06-03 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20200601_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
