# Generated by Django 3.0.7 on 2020-06-11 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_venda_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='total',
        ),
        migrations.RemoveField(
            model_name='encomendaproduto',
            name='total',
        ),
        migrations.AlterField(
            model_name='temporadaencomenda',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EncomendaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Encomenda')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.EntradaFinanceira')),
            ],
        ),
        migrations.AddField(
            model_name='encomenda',
            name='entradas',
            field=models.ManyToManyField(through='financeiro.EncomendaEntrada', to='financeiro.EntradaFinanceira'),
        ),
    ]
