# Generated by Django 3.0.7 on 2020-06-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20200611_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='entradas',
        ),
        migrations.DeleteModel(
            name='EncomendaEntrada',
        ),
    ]
