# Generated by Django 3.0.5 on 2020-04-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20200416_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretorioAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
            ],
        ),
    ]
