# Generated by Django 3.0.5 on 2020-04-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_diretorioacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretorioacademico',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
