# Generated by Django 3.0.5 on 2020-05-02 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_auto_20200424_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diretorioacademico',
            name='sigla',
            field=models.CharField(default='', max_length=10, verbose_name='Sigla do diretório acadêmico'),
        ),
        migrations.AlterField(
            model_name='diretorioacademico',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo do diretório'),
        ),
        migrations.AlterField(
            model_name='diretorioacademico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do diretório acadêmico'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='ata',
            field=models.TextField(verbose_name='Transcrição da ata...'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data da reunião'),
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.Area'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='associados',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
