# Generated by Django 3.0.5 on 2020-05-02 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_auto_20200502_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='associados',
            field=models.ManyToManyField(related_name='associados', to=settings.AUTH_USER_MODEL),
        ),
    ]
