# Generated by Django 3.0.5 on 2020-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_auto_20200502_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='ano_matricula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Matrícula'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='associado',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='É diretor?'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='matricula',
            field=models.CharField(max_length=30, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='previsao_conclusao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Previsão de Conclusão'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
