# Generated by Django 3.0.5 on 2020-05-03 12:22

from django.db import migrations, models
import gestao.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_auto_20200503_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=gestao.models.diretorio_usuario),
        ),
        migrations.AlterField(
            model_name='associado',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Não Formado?'),
        ),
    ]
