# Generated by Django 3.0.5 on 2020-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_auto_20200503_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='is_active',
            field=models.BooleanField(default=True, help_text='O associado ainda está estudado?', verbose_name='Aluno Ativo?'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='O associado faz parte da chapa eleita?', verbose_name='É diretor?'),
        ),
    ]
