# Generated by Django 3.0.6 on 2020-05-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_auto_20200515_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='associado',
            options={'verbose_name': 'Associado', 'verbose_name_plural': 'Associados'},
        ),
        migrations.AlterModelOptions(
            name='diretor',
            options={'verbose_name': 'Diretor', 'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='diretorioacademico',
            options={'verbose_name': 'Diretorio Acadêmico', 'verbose_name_plural': 'Diretorio Acadêmico'},
        ),
        migrations.AlterModelOptions(
            name='egresso',
            options={'verbose_name': 'Egresso', 'verbose_name_plural': 'Egressos'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'Reuniao', 'verbose_name_plural': 'Reunioes'},
        ),
    ]
