# Generated by Django 3.0.6 on 2020-05-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_auto_20200515_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
    ]
