# Generated by Django 3.0.6 on 2020-05-17 17:15

from django.db import migrations, models
import gestao.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_auto_20200517_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=36)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(default=gestao.models.mais_h)),
                ('tipo_usuario', models.PositiveIntegerField(choices=[(1, 'Diretor'), (2, 'Aluno'), (3, 'Egresso'), (4, 'Usuário Externo')])),
            ],
        ),
    ]
