# Generated by Django 3.0.6 on 2020-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_linkcadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcadastro',
            name='codigo',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
