# Generated by Django 3.0.6 on 2020-05-17 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_auto_20200517_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcadastro',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='linkcadastro',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
